complete -c svgdiff -f
complete -c svgdiff -n 'test (count (commandline -opc)) -le 2' -a '(__fish_complete_suffix .svg)' -d 'SVG input file'
complete -c svgdiff -n 'test (count (commandline -opc)) -le 2' -a '-' -d 'Read one SVG from stdin'
complete -c svgdiff -l width -r -d 'Comparison viewport width in CSS pixels'
complete -c svgdiff -l height -r -d 'Comparison viewport height in CSS pixels'
complete -c svgdiff -l max-checkpoints -r -d 'Optional deterministic computation budget'
complete -c svgdiff -l perceptual-background -r -d 'Record one explicit opaque deterministic sRGB background'
complete -c svgdiff -l flip-pixels-per-degree -r -d 'Request LDR-FLIP with supported pixels per degree'
complete -c svgdiff -l flip-error-threshold -r -d 'Report FLIP area above an explicit error threshold'
complete -c svgdiff -l before-resource -r -d 'Supply one before-side resource JSON object'
complete -c svgdiff -l after-resource -r -d 'Supply one after-side resource JSON object'
complete -c svgdiff -l output -r -F -d 'Write JSON or Agent projection JSONL to a file'
complete -c svgdiff -l html -r -F -d 'Write the self-contained HTML report'
complete -c svgdiff -l summary -r -F -d 'Write a derived non-authoritative Markdown summary'
complete -c svgdiff -l agent-json -d 'Emit whitespace-free canonical JSON'
complete -c svgdiff -l agent-projection -d 'Emit lossless line-addressable Agent projection JSONL'
complete -c svgdiff -l help -d 'Show command help'
complete -c svgdiff -l version -d 'Show component versions'
