complete -c svgdiff -f
complete -c svgdiff -n 'test (count (commandline -opc)) -le 2' -a '(__fish_complete_suffix .svg)' -d 'SVG input file'
complete -c svgdiff -n 'test (count (commandline -opc)) -le 2' -a '-' -d 'Read one SVG from stdin'
complete -c svgdiff -l width -r -d 'Comparison viewport width in CSS pixels'
complete -c svgdiff -l height -r -d 'Comparison viewport height in CSS pixels'
complete -c svgdiff -l perceptual-background -r -d 'Record one explicit opaque deterministic sRGB background'
complete -c svgdiff -l flip-pixels-per-degree -r -d 'Request LDR-FLIP with supported pixels per degree'
complete -c svgdiff -l before-resource -r -d 'Supply LOCATOR MEDIA_TYPE FILE for the before SVG'
complete -c svgdiff -l after-resource -r -d 'Supply LOCATOR MEDIA_TYPE FILE for the after SVG'
complete -c svgdiff -l output -r -F -d 'Write Structured Report JSON to a file'
complete -c svgdiff -l html -r -F -d 'Write the self-contained HTML report'
complete -c svgdiff -l agent-json -d 'Emit whitespace-free canonical JSON'
complete -c svgdiff -l help -d 'Show command help'
complete -c svgdiff -l version -d 'Show component versions'
